# Generated by Django 3.0.8 on 2020-07-16 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conjugate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=100)),
                ('lang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjugate.Language')),
            ],
        ),
    ]
