# Generated by Django 3.0.8 on 2020-07-16 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conjugate', '0002_verb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verb',
            old_name='lang_id',
            new_name='lang',
        ),
    ]
