# Generated by Django 3.0.8 on 2020-07-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conjugate', '0003_auto_20200715_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tense', models.CharField(max_length=100)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjugate.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjugate.Language')),
            ],
        ),
    ]
