# Generated by Django 3.0.8 on 2020-07-18 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conjugate', '0004_subject_tense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjugation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conj', models.CharField(max_length=200)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjugate.Language')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjugate.Subject')),
                ('tense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjugate.Tense')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjugate.Verb')),
            ],
        ),
    ]
